# **Tratamiento de errores**

### **try - except - finally:**
```py
try:
    num1 = 9
    num2 = 0
    result = num1 / num2
    print(result)
except:
    print("error")
finally:
    print("\nend")
```
### **Resultado:**
```sh
error

end
```
